### ISSUE TITLE
Unable to migrate Rails database on Heroku

### ISSUE THREAD

**Issue by danny-eng** [danny-eng/nutrition-app#3]
I am trying to host the project on Heroku. The React front-end works via buildpacks. The Rails back-end isn't migrating.

Normally (from what I understand), the CLI command would be:
```
$ heroku run rake db:migrate
```

However, this is the response I get:
```
$ heroku run rake db:migrate
Running rake db:migrate on ⬢ ancient-river-10106... up, run.6195 (Free)
rake aborted!
LoadError: cannot load such file -- bundler/setup
/app/config/boot.rb:3:in `<top (required)>'
/app/config/application.rb:1:in `require_relative'
/app/config/application.rb:1:in `<top (required)>'
/app/Rakefile:4:in `require_relative'
/app/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

The error log suggests that I am missing Bundler. That's impossible considering Ruby (and Bundler) is integrated into Heroku.

I Googled for answers; however, the responses I've gotten seem to focus on local hosting. Any help would be appreciated.

**Comment by danny-eng** [comment]
UPDATE: Heroku now accepts the command, but I'm still getting 404s when posting data to the API.

Moving to new issue ticket.
